spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 443
